version: 0.1

env:
  variables:
    VarName: "Value"
  parameter-store:
    EVAPI_PRIVATE_KEY: "EVAPI_PRIVATE_KEY"
    EVAPI_AUTHFILE: "EVAPI_AUTHFILE"
    EVAPI_BUCKET: "EVAPI_S3_BUCKET_NAME"
    EVAPI_ESPORT: "EVAPI_ELASTIC_PORT"
    EVAPI_ESHOST: "EVAPI_ELASTIC_HOST"
    EVAPI_ESNAME: "EVAPI_ELASTIC_NAME"
    EVAPI_TIMEOUT: "EVAPI_TIMEOUT"
    EVAPI_DEFAULT_SALT: "EVAPI_DEFAULT_SALT"
    EVAPI_AUTH_FILE: "EVAPI_AUTHFILE_LOCATION"
    EVAPI_PUBLIC_KEY_FILE: "EVAPI_PUBLIC_KEY_LOCATION"
    EVAPI_PRIVATE_KEY_FILE: "EVAPI_PRIVATE_KEY_LOCATION"
    EVAPI_ENDPOINT: "EVAPI_ENDPOINT"
    EVAPI_REGION: "EVAPI_REGION"
    EVAPI_SERVICENAME: "EVAPI_SERVICENAME"
phases:
  install:
    commands:
      - echo EV API install started on `date`
  pre_build:
    commands:
      - echo EV API pre-build started on `date`
      - mkdir /Users/
      - echo $EVAPI_AUTHFILE > /Users/authfile
      - echo $EVAPI_PRIVATE_KEY > /Users/private_key.pem
      - openssl pkcs8 -topk8 -inform PEM -outform DER -in /Users/private_key.pem -out /Users/private_key.der -nocrypt
      - openssl rsa -in /Users/private_key.pem -pubout -outform DER -out /Users/public_key.der
      - sed -i -e 's/BUCKETNAME/'$EVAPI_BUCKET'/g' src/main/resources/application.properties
      - sed -i -e 's/DEFAULTSALT/'$EVAPI_DEFAULT_SALT'/g' src/main/resources/application.properties
      - sed -i -e 's/TIMEOUT/'$EVAPI_TIMEOUT'/g' src/main/resources/application.properties
      - sed -i -e 's/ESNAME/'$EVAPI_ESNAME'/g' src/main/resources/application.properties
      - sed -i -e 's/ESHOST/'$EVAPI_ESHOST'/g' src/main/resources/application.properties
      - sed -i -e 's/ESPORT/'$EVAPI_ESPORT'/g' src/main/resources/application.properties
      - sed -i -e 's/AUTH_FILE/'$EVAPI_AUTH_FILE'/g' src/main/resources/application.properties
      - sed -i -e 's/PUBLIC_KEY/'$EVAPI_PUBLIC_KEY_FILE'/g' src/main/resources/application.properties
      - sed -i -e 's/PRIVATE_KEY/'$EVAPI_PRIVATE_KEY_FILE'/g' src/main/resources/application.properties
      - sed -i -e 's/ENDPOINT/'$EVAPI_ENDPOINT'/g' src/main/resources/application.properties
      - sed -i -e 's/REGION/'$EVAPI_REGION'/g' src/main/resources/application.properties
      - sed -i -e 's/SERVICENAME/'$EVAPI_SERVICENAME'/g' src/main/resources/application.properties
  build:
    commands:
      - echo EV API build started on `date`
      - mvn test
  post_build:
    commands:
      - echo EV API build completed on `date`
      - mvn package
artifacts:
  files:
    - target/evapi-0.0.1-SNAPSHOT.jar
  secondary-artifacts:
    artifact1:
      files:
        - /Users/authfile
    artifact2:
      files:
        - /Users/private_key.der
    artifact3:
      files:
        - /Users/public_key.der

