version: 0.1

phases:
  build:
    commands:
      - echo EV API build started on `date`
      - mvn test
  post_build:
    commands:
      - echo EV API build completed on `date`
      - mvn package
artifacts:
  files:
    - target/ev-api-1.0-SNAPSHOT.jar
